from web.components.connection_view import connection_view
from web.components.conversation_view import conversation_view
from web.components.entity_browser import entity_browser
from web.components.evaluate import evaluate_panel
from web.components.evaluate_upload import evaluate_upload_panel
from web.components.event_registry import event_registry
from web.components.export import export_panel
from web.components.load_mapping import load_mapping_panel
from web.components.mapping_editor import mapping_editor
from web.components.rule_hierarchy import rule_hierarchy
from web.components.save_mapping import save_panel
from web.components.session_dashboard import session_dashboard
from web.components.sidebar import sidebar
from web.components.span_tree import span_tree
from web.components.upload import upload_panel
